POST localhost:4000/patients
Content-Type: application/json

{
  "name": "Ranjana Awasthi",
  "email": "ranajanaAwasthi09@gmail.com",
  "address": "A-143/6 Baba Colony Burari",
  "dateOfBirth": "2001-07-21",
  "registeredDate": "2005-10-10"
}