PUT localhost:4000/patients/f07797ae-3a7c-4ea5-a745-6c3a29add1fe
Content-Type: application/json

{
  "name": "Piyush Awasthi",
  "email": "piyushawasthi09@gmailcom",
  "address": "934 Janta",
  "dateOfBirth": "2004-02-10",
  "registeredDate": "2007-10-10"
}